pub struct OAuthConfig {
    pub authorize_url: &'static str,
    pub token_url: &'static str,
    pub client_id_env: &'static str,
    pub client_secret_env: &'static str,
    pub scope: &'static str,
    pub extra_params: Option<&'static str>,
}

pub fn get_oauth_config(provider: &str) -> Option<OAuthConfig> {
    match provider {
        "slack" => Some(OAuthConfig {
            authorize_url: "https://slack.com/oauth/v2/authorize",
            token_url: "https://slack.com/api/oauth.v2.access",
            client_id_env: "SLACK_CLIENT_ID",
            client_secret_env: "SLACK_CLIENT_SECRET",
            scope: "chat:write,commands",
            extra_params: None,
        }),
        "github" => Some(OAuthConfig {
            authorize_url: "https://github.com/login/oauth/authorize",
            token_url: "https://github.com/login/oauth/access_token",
            client_id_env: "GITHUB_CLIENT_ID",
            client_secret_env: "GITHUB_CLIENT_SECRET",
            scope: "repo,user",
            extra_params: None,
        }),
        "google" => Some(OAuthConfig {
            authorize_url: "https://accounts.google.com/o/oauth2/v2/auth",
            token_url: "https://oauth2.googleapis.com/token",
            client_id_env: "GOOGLE_CLIENT_ID",
            client_secret_env: "GOOGLE_CLIENT_SECRET",
            scope: "https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/calendar.events",
            extra_params: Some("&response_type=code&access_type=offline&prompt=consent"),
        }),
        "microsoft" => Some(OAuthConfig {
            authorize_url: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            token_url: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            client_id_env: "MICROSOFT_CLIENT_ID",
            client_secret_env: "MICROSOFT_CLIENT_SECRET",
            scope: "offline_access Mail.ReadWrite Calendars.ReadWrite Files.ReadWrite.All",
            extra_params: Some("&response_mode=query"),
        }),
        "hubspot" => Some(OAuthConfig {
            authorize_url: "https://app.hubspot.com/oauth/authorize",
            token_url: "https://api.hubapi.com/oauth/v1/token",
            client_id_env: "HUBSPOT_CLIENT_ID",
            client_secret_env: "HUBSPOT_CLIENT_SECRET",
            scope: "crm.objects.contacts.read crm.objects.companies.read",
            extra_params: None,
        }),
        "salesforce" => Some(OAuthConfig {
            authorize_url: "https://login.salesforce.com/services/oauth2/authorize",
            token_url: "https://login.salesforce.com/services/oauth2/token",
            client_id_env: "SALESFORCE_CLIENT_ID",
            client_secret_env: "SALESFORCE_CLIENT_SECRET",
            scope: "api id openid",
            extra_params: Some("&response_type=code"),
        }),
        "jira" => Some(OAuthConfig {
            authorize_url: "https://auth.atlassian.com/authorize",
            token_url: "https://auth.atlassian.com/oauth/token",
            client_id_env: "JIRA_CLIENT_ID",
            client_secret_env: "JIRA_CLIENT_SECRET",
            scope: "read:jira-work write:jira-work offline_access",
            extra_params: Some("&audience=api.atlassian.com&prompt=consent"),
        }),
        "linear" => Some(OAuthConfig {
            authorize_url: "https://linear.app/oauth/authorize",
            token_url: "https://api.linear.app/oauth/token",
            client_id_env: "LINEAR_CLIENT_ID",
            client_secret_env: "LINEAR_CLIENT_SECRET",
            scope: "read write",
            extra_params: None,
        }),
        "notion" => Some(OAuthConfig {
            authorize_url: "https://api.notion.com/v1/oauth/authorize",
            token_url: "https://api.notion.com/v1/oauth/token",
            client_id_env: "NOTION_CLIENT_ID",
            client_secret_env: "NOTION_CLIENT_SECRET",
            scope: "",
            extra_params: None,
        }),
        "confluence" => Some(OAuthConfig {
            authorize_url: "https://auth.atlassian.com/authorize",
            token_url: "https://auth.atlassian.com/oauth/token",
            client_id_env: "CONFLUENCE_CLIENT_ID",
            client_secret_env: "CONFLUENCE_CLIENT_SECRET",
            scope: "read:confluence-content write:confluence-content offline_access",
            extra_params: Some("&audience=api.atlassian.com&prompt=consent"),
        }),
        _ => None,
    }
}
